language: node_js
node_js:
- '6.1'
before_script:
- npm install -g bower
- npm install
- bower install
- gem install sass
- gem install compass
script: gulp build -r
deploy:
  api_key:
    secure: mtVBve5cEAHx8vqh3tYlKAoCHpO0Dr3BvLQ5BpW6+bety6q6+8+DFpZHQ8/oFz+ksZ+ePuzXT4fHr55Gp2p++YAr+KSjGNmoDtjynsy92vQu7K6wfB4wnvAd30GQ0jEdXyQ+zyLZlvjZyscM3NHs57Oed7WJT+4ZPNfKmyNAijhHl42qF2BuEUwFcFFnMI23XuqIq73Eqx/FR2wd1kAX2xvHKhy7qn4Zr5UI60hopLSdY7eWc6lLtPVSHpDYmMic1ORXmOIy3oSjvkcs2gtM7t3GBDg4EeZncSkvfDrY1/hIKPV/KAqVEmdcAqRZRdslBUgdtpa5GaIWI6L7KsoT4Orzh/NnkWDuLFgYKqn7iYILX0p0AKkqRI80kNdFO3/VDCL8ADf2+CSsBIMAuctLv6VU3RCjbiX7zPtBhX2E++Hs2DKr1ANgv1G7DrqDWV3rzLIOy4VIKN472kXriy+b3AtrNrqGAikeoV9TTR6WihXg7hU0NfYRBS7TSFM5APqaTu5UO/uCOPIvVLC6gvAWKvdDsUNpv2lqhar9lPbVqNeBAX2aD+Au6Z0x+TPJycvynbxOOWrcv788gZn4OJuxUfHcxnv7tiINaLCnpjuJStZTWH8HLxMxdkEoCNJwPGO3RSwyvCXu8shdfTy7sGWpYT9e6a8zKyxqRNDpI3zgRmw=
