language: node_js
node_js:
- '6.1'
before_script:
- npm install -g bower
- npm install
- bower install
- gem install sass
- gem install compass
script: gulp build -r
deploy:
  api_key:
    secure: "KPp4W1UFfYGG/pgT6ZMm85KbtOPPVU/c6bTJNJL4RQ4VkC1BHvAWJwVEpFrMEH5nkIlV30kM64z5HOMZT+oNOwCeUjn1nGIU+6KZkJ2tmAYAB2EPtKVyGzO1s8kre0EM3iICrbk69yR0lJZNamordXaSq+/nVPXZtKzsXgZgkIveqxyVj45N7OLowGTx21ZmEqNaaYnhidhXCaJdCwBkXJz8kxQvsH9pcsfP/Qbe5e2l6bz0FI7B1YRIpa+N1OpmYlQX7LNr5eltL93a/gulxBhumsaUkRl7TrJIgB4kj05AsWr1f21kyTRHP6wCsSwJwGHhGARRDX+BJSmvsym4vwfTBhSrSoHrl8kBkx1iA6WIpbtfHrrVuxLdzC6Sx7bZifXkl3CpZTd8A5iYL1TRB/ouQk2w9ppPRPA9ztk8J2F9eun6k1Irtm+OUAiA51TU/OE3PKE85W9LGbojZJc65g+eTSDcfjtkuwTlTd0n3HoWGW9X/tzbutuv2E1b8XQyP4BI/hifOjoXnfEnNZz6bcyDiiX8++fNpkPWegX4PFyXklYDn3cMsIO9dmj5dyr12OCxiznjj0YTp3I6Pc0QpHpewHeuXDm98LuHMErFl3TerQONLfHXkgYKhjJ/gF6PwDyzIwHg7+zBkNDztcEcuZShGo49xmG0at67TDOl6NM="
