language: node_js
node_js:
- '6.1'
before_script:
- npm install -g bower
- npm install
- bower install
- gem install sass
- gem install compass
- gem install heroku
script: gulp build -r
deploy:
  api_key:
    secure: E8cdKrN7FdeF71Ki6vUEpOOHnUgvc8sDS8hnGJUPIm0+h1t5rje2NHzvuE0M02MknMortqkDoIrmfFgKHLHnlH6irDvU9qzYGqeX/gD6OKakziIGAj8ec1DeujhWZR7NAT9fGZoIBIJG4/c1YxgraxOhG9F/8ASYJRToUnH5cpWhr22SV1RP9XW18IfGjd6HQK3dvwbQ3TX97Ba57Sm7ek7Hn+pcE7guCAm+HsGzQDfdO6UUe5uWiGfoywDAomFRJX32/XN/fBOzdJBJh9xcNP0j9CGw0fWrQvYnzbKUAMi4qvbZe4dVww6KSFnEOZqTpBdD+xqOe05Lph1UWQHM7pNQ0skHXRDToifrWtOnxmJzZtxeZNpPsGD6bkhMJsAN/Zb1akP6o9FBie1IMONn2BrufJnsgjgSrjME/uUt8cxcvNrZ9gn4lhC0lmIu+hA/g/r8jtEF6fvnYHxVq/Dn59YY70x7VdPAHWn94fE3jv2WKxrpJpZNxZBZnvmsw8Jdc8sdBeM+wEYLGLTr9j3i1lMoiiTCXVLaO3weHE6WA8mlYxrLXAvLszpQg0GcGagXPK77b5yuQ/jF/ceDtVb8Loc8gnkKH2DtkO2yYrTMNC05Mvfc70whPsu63kDIx3LvR5kYBFrRrUpMYnOuqlyZYVVYxh5OhgJuS2/VKJRxhPU=
