language: node_js ruby
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"
rvm:
  - 2.2
  - jruby
  - rbx-2
install: gem install sass  
before_script:
  - npm install -g gulp
  - npm install -g gulp
script: gulp build -r